-- MySQL Script generated by MySQL Workbench
-- Fri Nov 14 09:19:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema summercamp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema summercamp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `summercamp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `summercamp` ;

-- -----------------------------------------------------
-- Table `summercamp`.`camp_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`camp_areas` (
  `area_id` INT NOT NULL AUTO_INCREMENT,
  `area_name` VARCHAR(100) NOT NULL,
  `capacity` INT NULL DEFAULT NULL,
  `available` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`area_id`),
  UNIQUE INDEX `area_name` (`area_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`activities` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `area_id` INT NULL DEFAULT NULL,
  `max_participants` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`activity_id`),
  INDEX `area_id` (`area_id` ASC) VISIBLE,
  CONSTRAINT `activities_ibfk_1`
    FOREIGN KEY (`area_id`)
    REFERENCES `summercamp`.`camp_areas` (`area_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`persons` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `person_type` ENUM('camper', 'employee') NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `registration_date` DATE NULL DEFAULT NULL,
  `admission_fee_paid` TINYINT(1) NULL DEFAULT NULL,
  `hire_date` DATE NULL DEFAULT NULL,
  `role` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`),
  UNIQUE INDEX `uq_person_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`activity_registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`activity_registration` (
  `registration_id` INT NOT NULL AUTO_INCREMENT,
  `activity_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `registered_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(20) NULL DEFAULT 'registered',
  PRIMARY KEY (`registration_id`),
  UNIQUE INDEX `uq_activity_person` (`activity_id` ASC, `person_id` ASC) VISIBLE,
  INDEX `person_id` (`person_id` ASC) VISIBLE,
  CONSTRAINT `activity_registration_ibfk_1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `summercamp`.`activities` (`activity_id`),
  CONSTRAINT `activity_registration_ibfk_2`
    FOREIGN KEY (`person_id`)
    REFERENCES `summercamp`.`persons` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`activity_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`activity_schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `activity_id` INT NOT NULL,
  `scheduled_date` DATE NOT NULL,
  `start_time` TIME NULL DEFAULT NULL,
  `end_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `activity_id` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `activity_schedule_ibfk_1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `summercamp`.`activities` (`activity_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`camp_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`camp_groups` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_code` VARCHAR(50) NULL DEFAULT NULL,
  `counselor_id` INT NULL DEFAULT NULL,
  `area_id` INT NULL DEFAULT NULL,
  `capacity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `group_code` (`group_code` ASC) VISIBLE,
  INDEX `counselor_id` (`counselor_id` ASC) VISIBLE,
  INDEX `area_id` (`area_id` ASC) VISIBLE,
  CONSTRAINT `camp_groups_ibfk_1`
    FOREIGN KEY (`counselor_id`)
    REFERENCES `summercamp`.`persons` (`person_id`),
  CONSTRAINT `camp_groups_ibfk_2`
    FOREIGN KEY (`area_id`)
    REFERENCES `summercamp`.`camp_areas` (`area_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_type` ENUM('product', 'utility') NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantity_in_stock` INT NULL DEFAULT '0',
  `restock_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_type` (`item_type` ASC, `name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`lost_and_found`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`lost_and_found` (
  `found_id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `date_found` DATE NULL DEFAULT NULL,
  `location_found` VARCHAR(150) NULL DEFAULT NULL,
  `status` ENUM('found', 'claimed', 'returned') NULL DEFAULT 'found',
  `claimed_by_person_id` INT NULL DEFAULT NULL,
  `claimed_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`found_id`),
  INDEX `claimed_by_person_id` (`claimed_by_person_id` ASC) VISIBLE,
  CONSTRAINT `lost_and_found_ibfk_1`
    FOREIGN KEY (`claimed_by_person_id`)
    REFERENCES `summercamp`.`persons` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `camper_id` INT NOT NULL,
  `counselor_id` INT NOT NULL,
  `rating` TINYINT NOT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `review_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `camper_id` (`camper_id` ASC) VISIBLE,
  INDEX `counselor_id` (`counselor_id` ASC) VISIBLE,
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`camper_id`)
    REFERENCES `summercamp`.`persons` (`person_id`),
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`counselor_id`)
    REFERENCES `summercamp`.`persons` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_type` ENUM('sale', 'order', 'payment', 'refund', 'adjustment') NOT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `related_camper_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  INDEX `related_camper_id` (`related_camper_id` ASC) VISIBLE,
  CONSTRAINT `transactions_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `summercamp`.`persons` (`person_id`),
  CONSTRAINT `transactions_ibfk_2`
    FOREIGN KEY (`related_camper_id`)
    REFERENCES `summercamp`.`persons` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `summercamp`.`transaction_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summercamp`.`transaction_lines` (
  `line_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT '1',
  `unit_price` DECIMAL(10,2) NOT NULL,
  `line_total` DECIMAL(12,2) GENERATED ALWAYS AS ((`quantity` * `unit_price`)) VIRTUAL,
  PRIMARY KEY (`line_id`),
  INDEX `transaction_id` (`transaction_id` ASC) VISIBLE,
  INDEX `item_id` (`item_id` ASC) VISIBLE,
  CONSTRAINT `transaction_lines_ibfk_1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `summercamp`.`transactions` (`transaction_id`)
    ON DELETE CASCADE,
  CONSTRAINT `transaction_lines_ibfk_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `summercamp`.`items` (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
